# Generated by Django 2.0 on 2020-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCreate', '0002_auto_20200502_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'new'), ('S', 'sale'), ('H', 'hot')], max_length=1, null=True),
        ),
    ]
